### ISSUE TITLE
504 Gateway Time-out and rank command didnt work anymore

### ISSUE THREAD

**Issue by Try2bgood** [yash1441/Chat-Valorant-Rank#12]
hi, if i use the generated code for streamelements it will tell me that it "Could not connect to remote server"
and if i use the link in the code it will show me: 504 Gateway Time-out

i guess the api is down?

thank you and you guys did a great job!

thank you!

**Comment by yash1441** [comment]
On going bug with Glitch, the service that hosts my code. No idea when it will be resolved because they seem really slow to reply to tickets. On top of that there are also issues with the backend API going down here and there but those are insignificant until the former gets fixed by Glitch.

**Comment by yash1441** [comment]
This issue is now fixed.
