### ISSUE TITLE
Server not Responding?

### ISSUE THREAD

**Issue by EternalInfinity** [yash1441/Chat-Valorant-Rank#3]
Hey Yash, 

i used your api url for EU to get the Rank information from a Valo account. 
Unfortunate the API Url is not responding anymore 😢 

Did you stopped the Support of the Server?

**Comment by yash1441** [comment]
Hey, I have actually shifted it to a free hosting since an year now so I guess it is giving some hiccups. Please try now and let me know if it works.

Edit: Replit seems to be no longer working properly as a free host. The API should work now but I am not sure till how long :(

**Comment by EternalInfinity** [comment]
Hey Yash,

API is working again thx for responding and fixing it 👍 
Will reopen if an issue will come up again.

**Comment by yash1441** [comment]
I have shifted the hosting from Replit to Glitch as they stopped allowing free deployments. Hence, the URL has been updated now.

**Comment by adx74** [comment]
Hello, is this still working? :/

**Comment by adx74** [comment]
Nvm, Valo api i think : https://status.henrikdev.xyz/

**Comment by yash1441** [comment]
Yup, it relies on Henrik's API which was down for some time. Will add this link for future queries so users are aware, thanks!
