### ISSUE TITLE
onlyRank command doesn't work

### ISSUE THREAD

**Issue by BichHang07** [yash1441/Chat-Valorant-Rank#5]
Hi,
I added this command and the normal one works just fine, but when I add ?onlyRank=true it doesn't work anymore.
Hope to hear from you soon :3

**Comment by yash1441** [comment]
I am not seeing an error when I am trying it using my account - https://splendid-groovy-feverfew.glitch.me/valorant/ap/Simon/Tan?onlyRank=true
May I see the url you are using?

**Comment by BichHang07** [comment]
Rank: ${customapi.https://splendid-groovy-feverfew.glitch.me/valorant/eu/name/uwu?onlyRank=true}
I just hid my name for comfort but the url without onlyRank=true does work

**Comment by BichHang07** [comment]
actually, now it works xddd I had to change the { } with ( ) but in the beginnning it seemed like the normal url without onlyRank wouldn't work with ( )
I'm sorry to have bothered you
