### ISSUE TITLE
Error when using link 

### ISSUE THREAD

**Issue by Koterak** [yash1441/Chat-Valorant-Rank#7]
Hello!
I was using you api for long time. For few weeks now I'm getting error 403 when trying to use link in Streamelements and also same happen when I'm trying to use it directly in browser.

Link which I'm using:
`$(customapi.https://splendid-groovy-feverfew.glitch.me/valorant/eu/wisteriarea/6464?onlyRank=true) `

I see that you changed redame but I see no difference in link. Did I miss something? I see same error when trying to use example link.

**Comment by ltrinch** [comment]
I have the same error. 
~~Using other APIs, I get the same error.~~ Nevermind, I get 400 error on other API.
![image (2)](https://github.com/yash1441/Chat-Valorant-Rank/assets/51722618/3789a686-c9d4-44c1-84bf-eb1e01edc9af)

**Comment by raimannma** [comment]
The Root API (henriks unofficial api) requires api key authentication now.

**Comment by yash1441** [comment]
I have applied for a key, it could come today. If not then it will probably be in June as Henrik is on holiday.

**Comment by yash1441** [comment]
For the time being, I used the basic key which restricts to 30 request per minute. It should work for now until the advance key request gets approved,

**Comment by yash1441** [comment]
For the time being, I used the basic key which restricts to 30 request per minute. It should work for now until the advance key request gets approved,
