### ISSUE TITLE
url wrong

### ISSUE THREAD

**Issue by Nitronturbo** [yash1441/Chat-Valorant-Rank#8]
should be $(customapi https://splendid-groovy-feverfew.glitch.me/valorant/region/name/tag)
There shouldnt be a "." in between customapi and https.

**Comment by Nitronturbo** [comment]
Also is it possible to get an mmrchange command.

**Comment by yash1441** [comment]
Added a more detailed usage section for each bot. As for the mmr change, creating a new ticket let's discuss there.
